import { atom, RecoilState } from 'recoil'

import { EncryptedFileInfo, DecryptedFileInfo } from '../util'

/**
 * @type {RecoilState<Uint8Array | null>}
 */
export const fileDataState = atom({
    key: 'fileData',
    default: null,
})

/**
 * @type {RecoilState<string | null>}
 */
export const fileNameState = atom({
    key: 'fileName',
    default: null,
})

/**
 * @type {RecoilState<string | null>}
 */
export const passwordState = atom({
    key: 'password',
    default: null,
})

/**
 * @type {RecoilState<boolean>}
 */
export const passwordAutogeneratedState = atom({
    key: 'passwordAutogenerated',
    default: false,
})

/**
 * @type {RecoilState<number | null>}
 */
export const expirySecondsState = atom({
    key: 'expirySeconds',
    default: null,
})

/**
 * @type {RecoilState<EncryptedFileInfo | null>}
 */
export const encryptedFileInfoState = atom({
    key: 'encryptedFileInfo',
    default: null,
})

/**
 * @type {RecoilState<EncryptedFileInfo | null>}
 */
export const downloadedFileInfoState = atom({
    key: 'downloadedFileInfo',
    default: null,
})

/**
 * @type {RecoilState<DecryptedFileInfo | null>}
 */
export const decryptedFileInfoState = atom({
    key: 'decryptedFileInfo',
    default: null,
})

/**
 * @type {RecoilState<string | null>}
 */
export const accessTokenState = atom({
    key: 'accessToken',
    default: null,
})

/**
 * @type {RecoilState<string | null>}
 */
export const updateTokenState = atom({
    key: 'updateToken',
    default: null,
})

/**
 * @type {RecoilState<boolean>}
 */
export const fileFullyUploadedState = atom({
    key: 'fileFullyUploaded',
    default: false,
})

/**
 * @type {RecoilState<boolean>}
 */
export const fileFullyDownloadedState = atom({
    key: 'fileFullyDownloaded',
    default: false,
})
