#
# Build env
#

FROM node:25-alpine

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
RUN npm ci

COPY public ./public
COPY src ./src

COPY .env.local ./

EXPOSE 3000
CMD ["npm", "run", "dev"]
