global:
  scrape_interval: 15s
  scrape_timeout: 15s

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: hdrop-backend
    metrics_path: /v1/metrics
    static_configs:
      - targets:
        - 'api:80'
