#
# Build env
#

FROM node:24-alpine

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
RUN npm ci

COPY public ./public
COPY src ./src

EXPOSE 3000
CMD ["npm", "run", "dev"]
