#
# Build env
#

FROM node:19-alpine

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./
RUN yarn --frozen-lockfile

COPY public ./public
COPY src ./src

EXPOSE 3000
CMD ["yarn", "start"]