// Generated by diesel_ext
use ::uuid::Uuid;
use chrono::{DateTime, Utc};
use diesel::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Default, Serialize, Deserialize, Debug, Queryable, Selectable, Identifiable, AsChangeset,
)]
#[diesel(primary_key(uuid))]
#[diesel(table_name = crate::schema::files)]
#[diesel(check_for_backend(diesel::pg::Pg))]
#[allow(non_snake_case)]
pub struct File {
    pub id: i32,
    pub uuid: Uuid,
    pub accessToken: String,
    pub updateToken: String,
    pub dataUrl: Option<String>,
    pub fileNameData: String,
    pub fileNameHash: String,
    pub salt: String,
    pub iv: String,
    pub createdAt: DateTime<Utc>,
    pub expiresAt: DateTime<Utc>,
}

#[derive(
    Default, Serialize, Deserialize, Queryable, Debug, Insertable, Identifiable, AsChangeset,
)]
#[diesel(primary_key(uuid))]
#[diesel(table_name = crate::schema::files)]
#[diesel(check_for_backend(diesel::pg::Pg))]
#[allow(non_snake_case)]
pub struct InsertFile {
    #[diesel(deserialize_as = i32)]
    pub id: Option<i32>,
    pub uuid: Uuid,
    pub accessToken: String,
    pub updateToken: String,
    pub dataUrl: Option<String>,
    pub fileNameData: String,
    pub fileNameHash: String,
    pub salt: String,
    pub iv: String,
    pub createdAt: DateTime<Utc>,
    pub expiresAt: DateTime<Utc>,
}

#[derive(Debug, Queryable, Selectable, Insertable, Identifiable)]
#[diesel(table_name = crate::schema::statistics)]
#[diesel(check_for_backend(diesel::pg::Pg))]
#[allow(non_snake_case)]
pub struct Statistic {
    pub id: i32,
    pub uploadCount: i32,
    pub deleteCount: i32,
    pub existCount: i32,
}
