[package]
name = "hdrop-shared"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
once_cell = "1.18"
paste = "1.0"

serde.workspace = true
thiserror.workspace = true
async-trait.workspace = true
