// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]
use chrono::NaiveDateTime;
use diesel::{AsChangeset, Identifiable, Insertable, Queryable};

#[derive(Debug, Clone)] // Queryable, Identifiable, Insertable, AsChangeset,
#[diesel(primary_key(uuid))]
#[diesel(table_name = crate::schema::files)]
pub struct File {
    pub id: i32,
    pub uuid: String,
    pub accessToken: String,
    pub updateToken: String,
    pub dataUrl: Option<String>,
    pub fileNameData: String,
    pub fileNameHash: String,
    pub salt: String,
    pub iv: String,
    pub createdAt: NaiveDateTime,
    pub expiresAt: NaiveDateTime,
}

#[derive(Debug)] // Queryable, Identifiable
#[diesel(table_name = crate::schema::statistics)]
pub struct Statistic {
    pub id: i32,
    pub uploadCount: i32,
    pub deleteCount: i32,
    pub existCount: i32,
}
