[package]
name = "hdrop-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
diesel = { version = "2.1.0", features = ["postgres", "chrono", "uuid"] }
diesel_migrations = "2.1.0"
chrono = {version = "0.4", features = ["serde"] }
uuid = { version = ">=0.7.0, <2.0.0", features = ["v4", "serde"] }
serde =  { version = "1", features = ["derive"] }
dotenvy = "0.15.7"
sha3 = "0.10.8"
parking_lot = "0.12.1"
deadpool-diesel = { version = "0.4.1", features = ["postgres"] }
deadpool = { version = "0.9.5", features = ["rt_tokio_1"] }
hdrop-shared = {path = "../hdrop-shared"}
